Makuinatzii/urls.py
from django.contrib import admin
from django.urls import path, include
from core import views
from django.contrib.auth import views as auth_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',views.home, name='inicio'),
    path('contacto/',views.contacto, name='contacto'),
    path('galeria/',views.galeria, name='galeria'),
    path('accounts/', include("django.contrib.auth.urls")),
    path('accounts/profile/', views.profile, name='profile'),
    path('', include('core.urls')),
    path('logout/', views.logout_view, name='logout'),
]

core/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('add/', views.formularioPublicacion, name='add_url'),
    path('edit/<int:fP_id>', views.updateView, name= 'update_url'),
    path('delete/<int:fP_id>', views.deleteView, name= 'delete_url'),
]

core/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Servicio(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=128, null=True, blank=True)
    imagen = models.ImageField(upload_to="core/static/img/serviciosImg")
    precio = models.IntegerField(default=999999)
    fechaSolicitado = models.DateField(null=True, blank=True)
    def __str__(self) -> str:
        return super().__str__()

class Publicacion(models.Model):
    id = models.AutoField(primary_key=True)
    titulo = models.CharField(max_length=30)
    descripcion = models.CharField(max_length=128, null=True, blank=True)
    imagen = models.ImageField(upload_to='core/static/img/postsImg')
    trabajo = models.ForeignKey(Servicio, related_name="servicioRealizado", on_delete=models.CASCADE, blank=True, null=True)
    idMecanico = models.ForeignKey(User, related_name="mecanicoActivo", on_delete=models.CASCADE, blank=True, null=True)
    ESTADO_DROP = (
        ('R', 'Rechazado'),
        ('P', 'Pendiente'),
        ('A', 'Aprobado'),)
    estado = models.CharField(max_length=10, choices=ESTADO_DROP, default='P')
    razonRechazo = models.CharField(max_length=256, null=True, blank=True)
    fecha = models.DateField()
    def __str__(self) -> str:
        return super().__str__()
    


core/forms.py
from django import forms
from .models import Publicacion
import datetime

class FormPublicacion(forms.ModelForm):
    class Meta:
        model = Publicacion
        fields = '__all__'

        labels = {
            'titulo': 'Titulo de Publicacion',
            'descripcion' : 'Descripcion de Publicacion',
            'imagen' : 'Imagen' ,
            'trabajo' : 'Servicio Realizado' ,
            'mecanico' : 'Mecanico',
            'fecha' : 'Fecha',
        }

        widgets  ={
            'titulo' : forms.TextInput(attrs={'placeholder': 'eg. Titulo'}),
            'descripcion' : forms.Textarea(attrs={'placeholder': 'eg. Descripcion'}),
            'trabajo' : forms.Select(),
            'imagen' : forms.ClearableFileInput(),
            'mecanico' : forms.Select(),
            'fecha' : forms.DateInput(attrs={'class':'datepicker', 'value': datetime.date.today()}),
        }

core/views.py
from django.shortcuts import render, redirect
from django.contrib.auth import authenticate, login
from core.models import Publicacion, Servicio
from core.forms import FormPublicacion
from django.contrib.auth.decorators import login_required
from django.contrib.auth import logout

# Create your views here.
def home(request):
    dataPosts = Publicacion.objects.all()
    dataServ = Servicio.objects.all()
    context = {'dataPosts': dataPosts, 'dataServ': dataServ}
    return render(request, 'core/index.html', context)

def contacto(request):
    return render(request, 'core/contacto.html')

def galeria(request):
    dataPosts = Publicacion.objects.all()
    context = {'dataPosts': dataPosts,
               'user': request.user,
               'groups': request.user.groups.all()}
    return render(request, 'core/galeria.html', context)

def registro(request):
    return render(request, 'core/registro.html')

@login_required(login_url="/accounts/login/")
def profile(request):
    context = {'user': request.user,
               'groups': request.user.groups.all()}
    return render(request, 'core/profile.html', context)

def formularioPublicacion(request):
    form = FormPublicacion()
    if request.method == 'POST':
        form = FormPublicacion(request.POST, request.FILES)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.save(user=request.user)
            return redirect('galeria')
    else:
        form = FormPublicacion(request.POST, request.FILES)
    context = {'form': form}
    return render(request, 'core/add.html', context)

def updateView(request, fP_id):
    pub = Publicacion.objects.get(id=fP_id)
    form = FormPublicacion(instance=pub)
    if request.method == 'POST':
        form = FormPublicacion(request.POST, request.FILES, instance=pub)
        if form.is_valid():
            form.save()
            return redirect('galeria')
    context = {'form': form}
    return render(request, 'core/add.html', context)

def deleteView(request, fP_id):
    pub = Publicacion.objects.get(id=fP_id)
    if request.method == 'POST':
        pub.delete()
        return redirect('galeria')
    context = {'pub': pub}
    return render(request, 'core/delete.html', context)

def logout_view(request):
    logout(request)
    return redirect('inicio')

core/templates/core/add.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
  
    <link href="{% static 'css/add.css' %}" rel="stylesheet">
  
    <title>Crear una nueva publicacion</title>
</head>
<body id="miBody">
    {% include 'core/navbar.html' %}    

    <div class="container">
        <div class="row justify-content-center mt-5">
            <div class="col-md-6">
                <div class="card">
                    <div class="card-body">
                        <h2 class="card-title text-center mb-4">Crear una publicación</h2>
                        <form method="post" class="needs-validation" novalidate>
                            
                            {% csrf_token %}
                            {{ form.as_p }}
                            <div class="form-group mt-3">
                                
                            
                              
                            </div>
                           
                            <button type="submit" class="btn btn-primary btn-block mt-3">Guardar Publicación</button>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>





    

    <!-- Bootstrap JS (opcional, si necesitas funcionalidades de Bootstrap que requieren JavaScript) -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-7vpvcvXkLq8mlispd0V6P9dJ1U0W5i2xZtkJ7WjRVYgNd3Xoy4qUsso2pZ3yWXS7" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/contacto.html
<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Página de Contacto</title>
    <!-- CSS CUSTOM -->
    {% load static %}
    <link href="{% static 'css/contacto.css' %}"  rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
</head>
<body class="Contacto-body">
    {% include 'core/navbar.html' %}

    <h1 class="text-center">CONTACTO</h1>
    <div class="container">
        <div class="row justify-content-center">
            <div class="col-md-6">
                <form id="form">
                    <div class="form-group">
                        <label for="inputName">Nombre</label>
                        <input type="Name" class="form-control" id="inputName" placeholder="Nombre" name="name" required>
                    </div>
                    <div class="form-group">
                        <label for="inputEmail4">Email</label>
                        <input type="email" class="form-control" id="inputEmail4" placeholder="Email" name="email" required>
                    </div>
                    <div class="form-group">
                        <label for="inputAddress">Dirección</label>
                        <input type="text" class="form-control" id="inputAddress" placeholder="Calle 123" name="direccion" required>
                    </div>
                    <div class="form-group">
                        <label for="inputServicio">Servicio</label>
                        <select class="form-control" id="inputServicio" name="servicio" required>
                            <option value="" disabled selected>Selecciona un servicio</option>
                            <option value="Servicio Técnico">Servicio Técnico</option>
                            <option value="Desabolladura y Pintura">Desabolladura y Pintura</option>
                            <option value="Repuestos">Repuestos</option>
                            <option value="Detallado">Detallado</option>
                        </select>
                    </div>
                    <div class="form-group">
                        <label for="inputComentario">Comentario</label>
                        <input type="text" class="form-control" id="inputComentario" placeholder="Comentario" name="comentario">
                    </div>
                    <div class="text-center mt-3">
                        <input type="submit" class="btn btn-primary" id="button" value="Enviar">
                    </div>
                </form>
                <script type="text/javascript" src="https://cdn.jsdelivr.net/npm/@emailjs/browser@4/dist/email.min.js"></script>
                <script type="text/javascript">
                    emailjs.init('BA_ws_FHRYcUGB2je'); // Crendencial de Martin
                </script>
            </div>
        </div>
    </div>
    
    <script src="js/formulario.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js" integrity="sha384-IQsoLXl5PILFhosVNubq5LC7Qb9DXgDA9i+tQ8Zj3iwWAwPtgFTxbJ8NT4GN1R8p" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js" integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF" crossorigin="anonymous"></script>
    

    
    </body>
    </html>
    

core/templates/core/delete.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- CSS CUSTOM -->
    {% load static %}
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Confirmacion de eliminacion</title>
</head>
<body>
    {% include 'core/navbar.html' %} 
    {% block content %}
        <div class="container">
            <form class="jumbotron" method="post">
                {% csrf_token %}
                <h2>Estas seguro que quieres borrar esta publicacion? </h2>
                <input type="submit" value="Si" class="btn btn-danger">
                <button class="btn btn-success"><a href="{% url 'galeria' %}">No</a></button>
            </form>
        </div>
    {% endblock %}
</body>
</html>

core/templates/core/galeria - copia.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS CUSTOM -->
  {% load static %}
  <link href="{% static 'css/galeria.css' %}"  rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Galeria</title>
</head>
<body>
  {% include 'core/navbar.html' %}    
      
<div class="row">
<div class="col-2" id="filtro">
  <h5 >Buscar por Mecanico </h5>
  <div class="form-group">
    <input type="text" class="form-control" id="palabraClave" placeholder="Palabra clave" style="width: 250px;">
  </div>
  <br>
  <label for="inputServicio"><b>Servicio</b></label>
  <select class="form-control" id="inputServicio" style="width: 250px;">
    <option value="" disabled selected>Selecciona un servicio</option>
    <option value="Servicio Técnico">Servicio Técnico</option>
    <option value="Desabolladura y Pintura">Desabolladura y Pintura</option>
    <option value="Repuestos">Repuestos</option>
    <option value="Detallado">Detallado</option>  
</select>
<br>
<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMecAll" checked>
  <label class="form-check-label" for="CheckMecAll">Mostrar Todo</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec1">
  <label class="form-check-label" for="CheckMec1">Mecánico 1</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec2">
  <label class="form-check-label" for="CheckMec2">Mecánico 2</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec3">
  <label class="form-check-label" for="CheckMec3">Mecánico 3</label>
</div>



<button type="button" class="btn btn-dark">Filtrar</button>
</div>

<div class="col-10" id="imageHolder">
  <div class="row row-cols-1 row-cols-md-5 g-4 align-items-stretch">
      <div class="col">
        <div class="card mecanico1"> 
          <img src="{% static 'img/2456710.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
              <a href="" class="stretched-link" data-bs-target="#modalPub1" data-bs-toggle="modal"></a>
              <h5 class="card-title">Nissan Vintage</h5>
              <p class="card-text">07/04/2024</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mecanico2"> 
          <img src="{% static 'img/2456711.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
              <a href="" class="stretched-link" data-bs-target="#modalPub2" data-bs-toggle="modal"></a>
              <h5 class="card-title">Trabajo 2</h5>
              <p class="card-text">07/04/2024</p>
          </div>
        </div>
      </div>
      <div class="col">
        <div class="card mecanico3"> 
          <img src="{% static 'img/2456712.jpg' %}" class="card-img-top" alt="...">
          <div class="card-body">
              <a href="" class="stretched-link" data-bs-target="#modalPub3" data-bs-toggle="modal"></a>
              <h5 class="card-title">Trabajo 3</h5>
              <p class="card-text">07/04/2024</p>
          </div>
        </div>
      </div>
    </div>




      <!-- MODALS-->
      <div class="modal fade" id="modalPub1" aria-hidden="true" aria-labelledby="modalPub1Label" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="modalPub1Label">NISSAN VINTAGE</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>

            <div class="modal-body">

              <img style="margin-bottom: 10px;" src="{% static 'img/2456710.jpg' %}" alt="">
              
              <h6> Detalles</h6>
              <p> Trabajo realizado: Mantención General</p>
                
            </div>

          </div>
        </div>
      </div>
      
      <div class="modal fade" id="modalPub2" aria-hidden="true" aria-labelledby="modalPub2Label" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
          <div class="modal-content">
            <div class="modal-header">
              <h1 class="modal-title fs-5" id="modalPub2Label">Trabajo 2</h1>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              <img style="margin-bottom: 10px;" src="{% static 'img/2456711.jpg' %}" alt="">
              <br>
              <h6> Detalles</h6>
              <p> Trabajo realizado: Mantención General</p>
            
            </div>
          </div>
        </div>
      </div>

      <div class="modal fade" id="modalPub3" aria-hidden="true" aria-labelledby="modalPub3Label" tabindex="-1">
        <div class="modal-dialog modal-dialog-centered">
            <div class="modal-content">
                <div class="modal-header">
                    <h1 class="modal-title fs-5" id="modalPub3Label">Trabajo 3 </h1>
                    <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
                </div>
                <div class="modal-body">
                    <img style="margin-bottom: 10px;" src="{% static 'img/2456712.jpg' %}" alt="">
                    <br>
                    <h6> Detalles</h6>
                    <p> Trabajo realizado: Mantención General</p>
                    
                </div>
            </div>
        </div>
    </div>
</div>

  <footer>
    <div>
      SOLO POR CUESTIONES DE DEBUG <a href="galeriaMecanico.html">Vista Mecanico</a>, <a href="galeriaAdministrador.html">Vista Administrador</a>
    </div>
  </footer>
</div>
  <script src="js/galeria.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>

core/templates/core/galeria.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <!-- CSS CUSTOM -->
  {% load static %}
  <link href="{% static 'css/galeria.css' %}"  rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <title>Galeria</title>
</head>
<body>
  {% include 'core/navbar.html' %}    
      
<div class="row">
<div class="col-2" id="filtro">
  <h5 >Buscar por Mecanico </h5>
  <div class="form-group">
    <input type="text" class="form-control" id="palabraClave" placeholder="Palabra clave" style="width: 250px;">
  </div>
  <br>
  <label for="inputServicio"><b>Servicio</b></label>
  <select class="form-control" id="inputServicio" style="width: 250px;">
    <option value="" disabled selected>Selecciona un servicio</option>
    <option value="Servicio Técnico">Servicio Técnico</option>
    <option value="Desabolladura y Pintura">Desabolladura y Pintura</option>
    <option value="Repuestos">Repuestos</option>
    <option value="Detallado">Detallado</option>  
</select>
<br>
<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMecAll" checked>
  <label class="form-check-label" for="CheckMecAll">Mostrar Todo</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec1">
  <label class="form-check-label" for="CheckMec1">Mecánico 1</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec2">
  <label class="form-check-label" for="CheckMec2">Mecánico 2</label>
</div>

<div class="form-check">
  <input class="form-check-input" type="radio" name="CheckMec" id="CheckMec3">
  <label class="form-check-label" for="CheckMec3">Mecánico 3</label>
</div>



<button type="button" class="btn btn-dark">Filtrar</button>
</div>

<!-- Cards -->
<div class="col-10" id="imageHolder">
  {% for group in groups %}
    {% if group.name == "Mecanico"  %}  
 <a type="button" class="btn btn-success float-end" href="{% url 'add_url' %}">Agregar</a>
    {% endif %}
    {% if group.name == "Manager"  %}  
 <a type="button" class="btn btn-success float-end" href="{% url 'add_url' %}">Agregar</a>
    {% endif %}
 {% endfor %}
  <div class="row row-cols-1 row-cols-md-5 g-4 align-items-stretch">
      {% if dataPosts %}
          {% for post in dataPosts %}
            {% if post.estado != "P" and post.estado != "R" %}
              <div class="col">
                <div class="card mecanico{{ post.idMecanico }}" id="{{post.id}}"> 
                  <img src="../{{post.imagen|cut:'core/'}}" class="card-img-top" alt="..." width="1280px" height="128px">
                  <div class="card-body">
                      <a href="" class="stretched-link" data-bs-target="#modalPub{{post.id}}" data-bs-toggle="modal"></a>
                      <h5 class="card-title">{{post.titulo}} </h5>
                      <p class="card-text">{{post.idMecanico}}  <br> <b>{{post.fecha}}</b> </p>
                  </div>
                </div>
              </div>
            {% else %}
              {% for group in groups %}
                {% if group.name == "Mecanico"  %}
                  {% if post.estado == "P" %}
                    <div class="col">
                      <div class="card pendiente bg-secondary text-white mecanico{{ post.idMecanico }}" id="{{post.id}}"> 
                        <img src="../{{post.imagen|cut:'core/'}}" class="card-img-top" alt="..." width="1280px" height="128px">
                        <div class="card-body">
                            <a href="" class="stretched-link" data-bs-target="#modalPub{{post.id}}" data-bs-toggle="modal"></a>
                            <h5 class="card-title">{{post.titulo}} </h5>
                            <p class="card-text">{{post.idMecanico}}  <br> <b>{{post.fecha}}</b> </p>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                  {% if post.estado == "R" %} 
                    <div class="col">
                      <div class="card pendiente bg-danger text-white mecanico{{ post.idMecanico }}" id="{{post.id}}"> 
                        <img src="../{{post.imagen|cut:'core/'}}" class="card-img-top" alt="..." width="1280px" height="128px">
                        <div class="card-body">
                            <a href="" class="stretched-link" data-bs-target="#modalPub{{post.id}}" data-bs-toggle="modal"></a>
                            <h5 class="card-title">{{post.titulo}} </h5>
                            <p class="card-text">{{post.idMecanico}}  <br> <b>{{post.fecha}}</b> </p>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                {% endif %}
                {% if group.name == "Manager" %}
                  {% if post.estado == "P" %}
                    <div class="col">
                      <div class="card pendiente bg-secondary text-white mecanico{{ post.idMecanico }}" id="{{post.id}}"> 
                        <img src="../{{post.imagen|cut:'core/'}}" class="card-img-top" alt="..." width="1280px" height="128px">
                        <div class="card-body">
                            <a href="" class="stretched-link" data-bs-target="#modalPub{{post.id}}" data-bs-toggle="modal"></a>
                            <h5 class="card-title">{{post.titulo}} </h5>
                            <p class="card-text">{{post.idMecanico}}  <br> <b>{{post.fecha}}</b> </p>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                  {% if post.estado == "R" %} 
                    <div class="col">
                      <div class="card pendiente bg-danger text-white mecanico{{ post.idMecanico }}" id="{{post.id}}"> 
                        <img src="../{{post.imagen|cut:'core/'}}" class="card-img-top" alt="..." width="1280px" height="128px">
                        <div class="card-body">
                            <a href="" class="stretched-link" data-bs-target="#modalPub{{post.id}}" data-bs-toggle="modal"></a>
                            <h5 class="card-title">{{post.titulo}} </h5>
                            <p class="card-text">{{post.idMecanico}}  <br> <b>{{post.fecha}}</b> </p>
                        </div>
                      </div>
                    </div>
                  {% endif %}
                  {% endif %}
              {% endfor %}

            {% endif %}
          {% endfor %}
      {% else %}
          <h1>No hay publicaciones disponibles...</h1>
      {% endif %}
      
  </div>

  <!-- MODAL-->
  {% for post in dataPosts %}
    <div class="modal fade" id="modalPub{{post.id}}" aria-hidden="true" aria-labelledby="modalPub{{post.id}}Label" tabindex="-1">
      <div class="modal-dialog modal-dialog-centered">
        <div class="modal-content">
          <div class="modal-header">
            <h1 class="modal-title fs-5" id="modalPub{{post.id}}Label">{{post.titulo}}</h1>
            <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
          </div>

          <div class="modal-body">
            <img style="margin-bottom: 10px;" src="../{{post.imagen|cut:'core/'}}" alt="">
            
            <h6>Detalles</h6>
            
            <p>{{post.descripcion}} <br>
              <b>Trabajo realizado:</b> {{post.trabajo.titulo}} <br>
              <b>Mecanico:</b> {{post.idMecanico}}</p>
              <b>Estado: {{post.get_estado_display}}</b>
              {% for group in groups %}
                {% if group.name == "Mecanico"  %}  
              <a type="button" class="btn btn-danger float-end" href="{% url 'delete_url' post.id %}">Eliminar</a>
              <a type="button" class="btn btn-warning float-end" href="{% url 'update_url' post.id %}">Editar</a>
                {% endif %}
                {% if group.name == "Manager"  %}  
                <a type="button" class="btn btn-danger float-end" href="{% url 'delete_url' post.id %}">Eliminar</a>
                <a type="button" class="btn btn-warning float-end" href="{% url 'update_url' post.id %}">Editar</a>
                {% endif %}
              {% endfor %}
          </div>
          
        </div>
      </div>
    </div>
  {% endfor %}

    




      
      
      
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js" integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.min.js" integrity="sha384-0pUGZvbkm6XF6gxjEnlmuGrJXVbNuzT9qBBavbLwCsOGabYfZo0T0to5eqruptLy" crossorigin="anonymous"></script>
</body>
</html>